config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :thanks
  resources :comments
  get 'pages/info'

  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
root to: redirect('/ideas')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :idea
    mount_uploader :picture, PictureUploader
    validates_presence_of :user_name, :body
end

app/models/idea.rb
class Idea < ApplicationRecord
    has_many :comments
    has_many :thanks
    mount_uploader :picture, PictureUploader
end

app/models/thank.rb
class Thank < ApplicationRecord
    belongs_to :idea
    validates_presence_of :user_name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Gravtastic
  gravtastic
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
#        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.html { redirect_to idea_path(@comment.idea_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
#    def comment_params
#      params.require(:comment).permit(:user_name, :body, :idea_id)
#    end
    def comment_params
       params.require(:comment).permit(:user_name, :body, :idea_id, :picture)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all.order(created_at: :desc)
    @cmtCount = 0
    @thankCount = 0
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @comments = @idea.comments.all
    @comment = @idea.comments.build
    
    @thanks = @idea.thanks.all
    @thank = @idea.thanks.build
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  before_action :set_thank, only: [:show, :edit, :update, :destroy]

  # GET /thanks
  # GET /thanks.json
  def index
    @thanks = Thank.all
  end

  # GET /thanks/1
  # GET /thanks/1.json
  def show
  end

  # GET /thanks/new
  def new
    @thank = Thank.new
  end

  # GET /thanks/1/edit
  def edit
  end

  # POST /thanks
  # POST /thanks.json
  def create
    @thank = Thank.new(thank_params)

    respond_to do |format|
      if @thank.save
        format.html { redirect_to @thank, notice: 'Thank was successfully created.' }
        format.json { render :show, status: :created, location: @thank }
      else
        format.html { render :new }
        format.json { render json: @thank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thanks/1
  # PATCH/PUT /thanks/1.json
  def update
    respond_to do |format|
      if @thank.update(thank_params)
        format.html { redirect_to @thank, notice: 'Thank was successfully updated.' }
        format.json { render :show, status: :ok, location: @thank }
      else
        format.html { render :edit }
        format.json { render json: @thank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thanks/1
  # DELETE /thanks/1.json
  def destroy
    @thank.destroy
    respond_to do |format|
      format.html { redirect_to thanks_url, notice: 'Thank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thank
      @thank = Thank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thank_params
      params.require(:thank).permit(:user_name, :idea_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name, id: :comment_user_name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>
  
  <div class="field">
  <%= form.label :picture %><br>
  <%= form.file_field :picture %>
  </div>
  
  <%= form.hidden_field :idea_id %>

  <div class="actions">
    <%= form.submit :class => 'btn btn-primary btn2 col-md-3 col-md-offset-9'%>
  </div>
<% end %>
<style>
  .btn2 {
    background-color: #428bca;
  }
  textarea {
    width: 100%;
    height: 100px;
  }
</style>

app/views/comments/edit.html.erb
<div class="block">
    <h1>Editing Comment</h1>

    <%= render 'form', comment: @comment %>
    <div class="row">
        <div class="btn"> <img src="https://cdn3.iconfinder.com/data/icons/edition/100/pen_2-128.png"/> <%= link_to 'Show', @comment %> | </div>
        <div class="btn"> <img src="https://cdn2.iconfinder.com/data/icons/social-messaging-productivity-1/128/reply-128.png"/> <%= link_to 'Back', comments_path %> </div>
    </div>
</div>

app/views/comments/index.html.erb
<div class="block">
  <p id="notice"><%= notice %></p>
  
  <h1>Comments</h1>
  
  <table>
    <thead>
      <tr>
        <th>User name</th>
        <th>Body</th>
        <th>Idea</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td style="vertical-align: top;"><%= comment.user_name %></td> 
          <td style="text-align: justify;"><%= comment.body %></td>
          <td style="vertical-align: top;"><%= comment.idea_id %></td>
          <td style="vertical-align: top;"><%= link_to 'Show', comment %></td>
          <td style="vertical-align: top;"><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td style="vertical-align: top;"><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  <div class="row">
    <div class="btn"> <img src="https://cdn0.iconfinder.com/data/icons/basic-ui-elements-plain/485/07_plus-128.png"/><%= link_to 'New Comment', new_comment_path %> </div>
  </div>
</div>

app/views/comments/new.html.erb
<div class="block">
    <h1>New Comment</h1>
    
    <%= render 'form', comment: @comment %>
    <div class="row">
        <div class="btn"> <img src="https://cdn2.iconfinder.com/data/icons/social-messaging-productivity-1/128/reply-128.png"/><%= link_to 'Back', comments_path %> </div>
    </div>
</div>

app/views/comments/show.html.erb
<div class="block">
 
  
  <p>
    <strong>User name:</strong>
    <p><%= @comment.user_name %></p>
  </p>
  
  <p>
    <strong>Body:</strong>
    <p><%= @comment.body %></p>
  </p>
  
  <p>
    <strong>Idea:</strong>
    <p><%= @comment.idea_id %></p>
  </p>
  
  <div class="row">
    <div class="btn"> <img src="https://cdn3.iconfinder.com/data/icons/edition/100/pen_2-128.png"/> <%= link_to 'Edit', edit_comment_path(@comment) %> | </div>
    <div class="btn"> <img src="https://cdn2.iconfinder.com/data/icons/social-messaging-productivity-1/128/reply-128.png"/> <%= link_to 'Back', comments_path %> </div>
  </div>
</div>

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :idea_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :idea_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :idea_picture %>
  </div>

  <div class="row actions" style="padding: 0 15px;">
    <%= form.submit :class => 'btn btn-primary btn2 col-md-3 col-md-offset-9'%>
  </div>
<% end %>
<style>
  label {
    width: 30%;
    float: left;
  }
  input, textarea {
    width: 70%;
  }
  .btn2 {
    background-color: #428bca;
  }
</style>

app/views/ideas/edit.html.erb
<div class="block" >
    <h1>Editing Idea</h1>

    <%= render 'form', idea: @idea %>
    <div class="row">
        <div class="btn"> <img src="https://cdn4.iconfinder.com/data/icons/glyphs/24/icons_view-128.png"/><%= link_to 'Show', @idea %> | </div>
        <div class="btn"> <img src="https://cdn2.iconfinder.com/data/icons/social-messaging-productivity-1/128/reply-128.png"/><%= link_to 'Back', ideas_path %> </div>
    </div>
</div>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>
<% @ideas.each do |idea| %>
<% @cmtCount = 0 %>
<% @thankCount = 0 %>
<div class="block">
  <div class="row idea-title">
    <img src="https://cdn4.iconfinder.com/data/icons/education-and-school-flat-icons/512/lightbulb_lamp_idea_ideas_education_equipment_learning_object_school_item_college_flat_icon_symbol-128.png" />
    <a href="/"><%= idea.name %></a>
  </div>
  <div class="row idea-img">
    <%= image_tag idea.picture_url(:thumb) if idea.picture? %>
    
    <div class="mini">
      <% idea.thanks.each do |thk| @thankCount += 1 end%>
    <p><img src="https://cdn0.iconfinder.com/data/icons/squarico/135/squarico-08-128.png" style="width:20px; margin: 0px 15px; padding:0"><%= @thankCount%> Thanks</p>
    </div><br/>
    
    <div class="mini">
     <% idea.comments.each do |cmt| @cmtCount += 1 end%>
    <p><img src="https://cdn2.iconfinder.com/data/icons/mixed-rounded-flat-icon/512/chat-128.png" style="width:20px; margin: 0px 15px; padding:0;"><%= @cmtCount%> Comments</p>
    </div>
    <p><b>Description</b></p>
    <p><%= idea.description %></p>
  </div>
  
  <div class="row idea-btn">
    <div class="btn"> <img src="https://cdn4.iconfinder.com/data/icons/glyphs/24/icons_view-128.png"/> <%= link_to 'Show', idea %> </div>
    <div class="btn"> <img src="https://cdn3.iconfinder.com/data/icons/edition/100/pen_2-128.png"/> <%= link_to 'Edit', edit_idea_path(idea) %> </div>
    <div class="btn"> <img src="https://cdn0.iconfinder.com/data/icons/basic-ui-elements-plain/385/010_x-128.png"/> <%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %> </div>
  </div>
</div>
<% end %>
<% if false %> <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= image_tag idea.picture_url, width: '100%' if idea.picture.present? %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<script>
    $(".fst").removeClass("left-item-active");
    $(".crt").addClass("left-item-active");
</script>
<div class="block">
<h1>New Idea</h1>
    
    <%= render 'form', idea: @idea %>
    
    <%= link_to 'Back', ideas_path %>
</div>

app/views/ideas/show.html.erb
<div class="block">

  
  <p>
    <strong>Name:</strong>
    <%= @idea.name %>
  </p>
  
  <p>
    <strong>Description:</strong>
    <%= @idea.description %>
  </p>
  
  <p>
    <strong>Picture:</strong>
    <%= image_tag(@idea.picture_url, :class => 'idea_picture' ) if @idea.picture.present?%>
    <h3><img src="https://cdn0.iconfinder.com/data/icons/squarico/135/squarico-08-128.png" style="width:30px; margin: 0px 15px;">Thanks</h3>
  <% @thanks.each do |thank| %>
    <div>
      <strong><%= thank.user_name %></strong> has thanks this idea
      <br />
      <p><%= link_to 'Delete', thank_path(thank), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
  <% end %>
  <%= render partial: 'thanks/form', locals: { thank: @thank } %>
    <h3><img src="https://cdn2.iconfinder.com/data/icons/mixed-rounded-flat-icon/512/chat-128.png" style="width:30px; margin: 0px 15px;">Comments</h3>
  <% @comments.each do |comment| %>
    <div>
      <strong><%= comment.user_name %></strong>
      <br />
      <p><%= comment.body %></p>
      <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
  <% end %>
  <%= render partial: 'comments/form', locals: { comment: @comment } %>
  </p>
  <div class="row">
    <div class="btn"> <img src="https://cdn3.iconfinder.com/data/icons/edition/100/pen_2-128.png"/><%= link_to 'Edit', edit_idea_path(@idea) %> | </div>
    <div class="btn"> <img src="https://cdn2.iconfinder.com/data/icons/social-messaging-productivity-1/128/reply-128.png"/> <%= link_to 'Back', ideas_path %> </div>
  </div>
</div>
<style>
  .idea_picture {width:100%;}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First project with Rails</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="head-navbar">
      <div class="container">
        <div class="navbar-header">
          
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/" style="color: white; font-family: Helvetica, Arial, sans-serif; font-size: 14px;">
            <img src="https://cdn3.iconfinder.com/data/icons/pet-shop-flat-colorful/614/5178_-_Paws-128.png" style="width: 50px; margin-top: -12px; float: left;"/>
            The Idea app</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a class="head-item-1st active" href="/ideas" style=" font-family: Helvetica, Arial, sans-serif; color: white;">Ideas</a></li>
            <li><a class="head-item-2nd" href="/pages/info"  style="color: white;  font-family: Helvetica, Arial, sans-serif">Info</a></li>
          </ul>
          <p class="navbar-text pull-right" style="color: white;">
              <div class="col-md-1 dropdown" style="float: right">
              <% if user_signed_in? %>
                <div class="dropdown" style="float: right; color: white;">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" type="button" id="dropdownMenuButton" data-toggle="dropdown" style="color: white">
                  <%= image_tag current_user.gravatar_url, :class => 'ava', :style => 'width: 30px;' %> <strong><%= current_user.email %></strong></button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <ul style="padding:0; margin:0; list-style: none;">
                      <li style="padding: 10px 20px;cursor:pointer;"><%= link_to "Edit profile", edit_user_registration_path, :class => 'dropdown-item' %></li>
                      <li style="padding: 10px 20px;"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %></li>
                    </ul>
                  </div>
                </div>
  
              <% else %>
              
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link', :class => 'navlink', :class => 'dropdown-item'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link', :class => 'navlink', :class => 'dropdown-item'  %>
              <% end %>
              </div></p>
        </div>
      </div>
</nav>
  <div class="container">
    <div class="col-md-2" style="position: fixed; padding:0">
      <ul  style="padding:0; padding-top: 50px;">
        <li class="left-item left-item-active fst"><img src="https://cdn0.iconfinder.com/data/icons/ballicons/128/lightbulb-128.png" class="item-img"/><a href="/ideas">Ideas</a></li>
        <li class="left-item crt"><img src="https://cdn4.iconfinder.com/data/icons/keynote-and-powerpoint-icons/256/Plus-128.png" class="item-img"/><a href="/ideas/new">Create new ideas</a></li>
        <li class="left-item pages"><img src="https://cdn4.iconfinder.com/data/icons/iconsimple-interface/512/information-128.png" class="item-img"/><a href="/pages/info">Info</a></li>
      </ul>
    </div>
    <div class="col-md-6 col-md-offset-2" style="padding: 0px;">
      <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %></div>
  </div>
  
  <footer>
  <div class="container">
    Rails Girls <%= Time.now.year %>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/pages/info.html.erb
<script>
    $(".fst").removeClass("left-item-active");
    $(".pages").addClass("left-item-active");
    $(".head-item-1st").removeClass("active");
    $(".head-item-2nd").addClass("active");
</script>
<div class="block">
    <h1>Pages info</h1>
    <p>Find me in app/views/pages/info.html.erb</p>
    <h2 style="text-align:center; color: coral">Welcome to my first Rails page</h2>
    <p style="text-align: center">Framgia Ruby on Rails girls </p>
</div>

app/views/thanks/_form.html.erb
<%= form_with(model: thank, local: true) do |form| %>
  <% if thank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thank.errors.count, "error") %> prohibited this thank from being saved:</h2>

      <ul>
      <% thank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name, id: :thank_user_name %>
  </div>
  
  
<%= form.hidden_field :idea_id %>


  <div class="actions">
    <%= form.submit  :class => 'btn btn-primary btn2 col-md-3 col-md-offset-9'%>
  </div>
<% end %>

app/views/thanks/edit.html.erb
<h1>Editing Thank</h1>

<%= render 'form', thank: @thank %>

<%= link_to 'Show', @thank %> |
<%= link_to 'Back', thanks_path %>

app/views/thanks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thanks</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Idea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thanks.each do |thank| %>
      <tr>
        <td><%= thank.user_name %></td>
        <td><%= thank.idea_id %></td>
        <td><%= link_to 'Show', thank %></td>
        <td><%= link_to 'Edit', edit_thank_path(thank) %></td>
        <td><%= link_to 'Destroy', thank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thank', new_thank_path %>

app/views/thanks/new.html.erb
<h1>New Thank</h1>

<%= render 'form', thank: @thank %>

<%= link_to 'Back', thanks_path %>

app/views/thanks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @thank.user_name %>
</p>

<p>
  <strong>Idea:</strong>
  <%= @thank.idea_id %>
</p>

<%= link_to 'Edit', edit_thank_path(@thank) %> |
<%= link_to 'Back', thanks_path %>